### ISSUE TITLE
Timezone-trouble

### ISSUE THREAD

**Issue by ADoebeling** [ADoebeling/contaoIcalExport#1]
- Export works fine with Outlook 2016 (with and without timezone-settings)
- @Samsung Galaxy S6 doesn't parses CET correct.

**Comment by LBeckX** [comment]
Reminder

**Comment by ADoebeling** [comment]
* [ ] bitte Code-Review https://github.com/ADoebeling/contaoIcalExport/pull/2
* [ ] Bitte bei CSU-ER patchen
* [ ] Bitte dann Pull-request bestätigen

**Comment by LBeckX** [comment]
@ADoebeling bitte 4AC
